<a href="https://colab.research.google.com/github/mendoncalan/Data_structure_python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arrays vs Lists

In [4]:
import numpy as np

In [2]:
L= [1,2,3]

In [3]:
A= np.array([1,2,3])

In [5]:
for e in L:
  print(e)


1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


Adding New item to the list

In [7]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

*Size of Lsit can change but the Size of Numpy Array is fixed*

In [10]:
L +[5]

[1, 2, 3, 4, 5]

In [11]:
L

[1, 2, 3, 4]

In [12]:
A+np.array([4]) # it will add 4 to each element in A

array([5, 6, 7])

In [13]:
A + np.array([4,5,6])#it will do vector addition


array([5, 7, 9])

In [14]:
2* A # it multip 2 to alll the element in np.array

array([2, 4, 6])

In [15]:
2 *L # it will repeat L element 2 times

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
# Add 3 to all the element in L
L2=[]
for e in L:
  L2.append(e+3)

In [18]:
L2

[4, 5, 6, 7]

In [19]:
l2= [e+3 for e in L]# List comprehension

In [20]:
L2

[4, 5, 6, 7]

In [21]:
L2 =[]
for e in L:
  L2.append(e**2)

In [22]:
L2

[1, 4, 9, 16]

In [23]:
A**2

array([1, 4, 9])

In [24]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

The Dot Product

In [28]:
a = np.array([1,2])

In [29]:
b= np.array([3,4])

In [30]:
dot =0
for e , f in zip(a,b): # zip() function is a python built in function for combining Multiple iterable object like List, tuples or string into a single iterable Tuples. https://www.codecademy.com/article/python-zip-function
  dot+=e*f

In [31]:
dot

np.int64(11)

In [35]:
dot=0
for i in range(len(a)):
  dot+= a[i]*b[i]


In [36]:
dot

np.int64(11)

In [37]:
a*b

array([3, 8])

In [38]:
np.sum(a*b)

np.int64(11)

In [39]:
(a*b).sum()

np.int64(11)

In [40]:
np.dot(a,b)

np.int64(11)

In [41]:
a.dot(b)

np.int64(11)

In [42]:
a @ b

np.int64(11)