<a href="https://colab.research.google.com/github/mendoncalan/Data_structure_python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arrays vs Lists

In [4]:
import numpy as np

In [2]:
L= [1,2,3]

In [3]:
A= np.array([1,2,3])

In [5]:
for e in L:
  print(e)


1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


Adding New item to the list

In [7]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

*Size of Lsit can change but the Size of Numpy Array is fixed*

In [10]:
L +[5]

[1, 2, 3, 4, 5]

In [11]:
L

[1, 2, 3, 4]

In [12]:
A+np.array([4]) # it will add 4 to each element in A

array([5, 6, 7])

In [13]:
A + np.array([4,5,6])#it will do vector addition


array([5, 7, 9])

In [14]:
2* A # it multip 2 to alll the element in np.array

array([2, 4, 6])

In [15]:
2 *L # it will repeat L element 2 times

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
# Add 3 to all the element in L
L2=[]
for e in L:
  L2.append(e+3)

In [18]:
L2

[4, 5, 6, 7]

In [19]:
l2= [e+3 for e in L]# List comprehension

In [20]:
L2

[4, 5, 6, 7]

In [21]:
L2 =[]
for e in L:
  L2.append(e**2)

In [22]:
L2

[1, 4, 9, 16]

In [23]:
A**2

array([1, 4, 9])

In [24]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [25]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

The Dot Product

In [28]:
a = np.array([1,2])

In [29]:
b= np.array([3,4])

In [30]:
dot =0
for e , f in zip(a,b): # zip() function is a python built in function for combining Multiple iterable object like List, tuples or string into a single iterable Tuples. https://www.codecademy.com/article/python-zip-function
  dot+=e*f

In [31]:
dot

np.int64(11)

In [35]:
dot=0
for i in range(len(a)):
  dot+= a[i]*b[i]


In [36]:
dot

np.int64(11)

In [37]:
a*b

array([3, 8])

In [38]:
np.sum(a*b)

np.int64(11)

In [39]:
(a*b).sum()

np.int64(11)

In [40]:
np.dot(a,b)

np.int64(11)

In [41]:
a.dot(b)

np.int64(11)

In [42]:
a @ b

np.int64(11)

**Matrices**

In [43]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [50]:
for i in range( 0, len(L)):
  for j in range(0, len(L[i])):
    print(L[i][j])


1
2
3
4


In [51]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [52]:
A[:,0]

array([1, 3])

In [54]:
A.T #It give transpose of Matrix A

array([[1, 3],
       [2, 4]])

In [55]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [56]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [59]:
B= np.array([[2,4,6],[3,5,6]])
B

array([[2, 4, 6],
       [3, 5, 6]])

In [60]:
A.dot(B)

array([[ 8, 14, 18],
       [18, 32, 42]])

In [61]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

Linear Systems

In [62]:
a =np.array([[1,1],[1.5,4]])
b= np.array([2200,5050])

In [63]:
np.linalg.solve(a,b)

array([1500.,  700.])

Generating DAta

In [64]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
10*np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.random.random((2,3))

array([[0.34079951, 0.75947186, 0.5257967 ],
       [0.70691155, 0.98121872, 0.96043236]])

In [71]:
np.random.randn(2,3)# to get number from Normal distribution

array([[-0.00849807,  2.46500418,  0.31619577],
       [ 0.52925558, -0.93178079,  0.09997658]])

In [76]:
R = np.random.randn(10000)

In [77]:
R.mean()

np.float64(-0.0008035685748674076)

In [78]:
np.mean(R)

np.float64(-0.0008035685748674076)

In [79]:
R.var()

np.float64(0.9995362106399767)

In [80]:
R.std()

np.float64(0.9997680784261801)

In [81]:
R = np.random.randn(10000,3)

In [82]:
R.mean(axis=0)

array([0.00038596, 0.00331604, 0.00597545])

In [83]:
R.mean(axis=1)

array([ 0.01300305,  0.24988911,  0.04232417, ..., -0.67437349,
        0.5879251 , -0.68378091])

In [84]:
np.cov(R)

array([[ 3.77952889,  0.75234454, -0.99911095, ..., -1.28395454,
        -0.7229837 ,  1.02663232],
       [ 0.75234454,  0.74067184, -0.04800148, ..., -0.8315012 ,
         0.64750022,  0.77004822],
       [-0.99911095, -0.04800148,  0.30263747, ...,  0.19235941,
         0.39319388, -0.12694911],
       ...,
       [-1.28395454, -0.8315012 ,  0.19235941, ...,  0.99748457,
        -0.52573026, -0.90009747],
       [-0.7229837 ,  0.64750022,  0.39319388, ..., -0.52573026,
         1.19825226,  0.56125076],
       [ 1.02663232,  0.77004822, -0.12694911, ..., -0.90009747,
         0.56125076,  0.82040682]])

In [85]:
np.cov(R).shape

(10000, 10000)

In [87]:
(R.T).shape

(3, 10000)

In [88]:
np.cov(R.T)

array([[ 1.00981873,  0.00285752, -0.00623937],
       [ 0.00285752,  1.01404116,  0.01663934],
       [-0.00623937,  0.01663934,  1.01028209]])

In [89]:
np.random.randint(0,10,size=(3,3))

array([[0, 8, 7],
       [4, 6, 6],
       [2, 8, 9]])

In [90]:
np.random.choice(10, size=(3,3))

array([[1, 2, 2],
       [5, 7, 1],
       [0, 3, 2]])